# Generated by Django 3.1.1 on 2021-01-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Quiz',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='question',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title',
            new_name='question',
        ),
    ]
